### ISSUE TITLE
Adapt Ladder Map Pool to Player Skill

### ISSUE THREAD

**Issue by Orb370** [FAForever/server#520] opened 2020-01-22 03:15 UTC
Hello,

I'm not sure this is in the right repository but I was talking with some folks on FAF and came upon this idea.

Forged Alliance is unique as an RTS in that the game can be vastly harder depending on the map. There's a lot of map variety.

I think for new players joining ladder this can be a bad experience. The 20x20 maps are really intimidating and players can get overwhelmed. There's also weird maps that start you with 1 core mex , but you need to use reclaim to supplement your income. Those aren't really newbie friendly.

Anecdotally, I find the 20x20 maps too difficult and often opt for team games these days as a result.

I would recommend different map pools for different ranks. For example, there should be mostly 5x5 maps and some easy 10x10 maps for <1000 rank. 1700+ should have more of the larger 20x20 maps.

**Comment by FtXCommando** [comment] 2020-01-27 18:55
Hey, I'm the Player Councillor (and therefore in charge of ladder) so I was informed of your suggestion. This is an idea that has definitely been floating around and has been suggested in the past. I used to hold the opinion that the discrepancy it would introduce to trueskill (people would never learn to properly macro on 20x20 scale if they rarely play them, the awkwardness of being on the cusp and essentially having to know two different map pools) were too large for the idea to be worth implementing. 

I now feel that the idea would be something that warrants trying out as we can always measure the metrics to see if the additional workload of managing several pools actually leads to any noteworthy increase in ladder playerbase. However, the problem is that I don't really think this is something that can be said will definitively lead to an increase in player participation on the ladder. I fall into the camp that a lot of people just are not interested in 1v1 games because of a combination of not finding them fun, seeing them as stressful, not enjoying the maps, etc. We see in games like starcraft 2 (where ladder play could be considered the most marketed part of the game scene) that the population that plays the 1v1 ladder is always smaller than the people playing teamgames. 

So the case study of other games leads me to the conclusion that the idea is not likely to suddenly change the dynamic between teamgames and ladder. While this may lead to an increase in say a couple dozen of ladder games each month, is it going to be worth not only the increase in my manpower, but is it going to be worth the dev manpower? I do not believe it is, and even though I would love to test out the idea, I would rather we spend resources on other aspects of the client/server.

**Comment by Orb370** [comment] 2020-01-29 01:06
Thanks for the well thought out response.

I remember ladder used to have a map ban option. What happened to it?

**Comment by Geosearchef** [comment] 2020-01-29 21:19
Concerning dev power, this a drop on a hot stove when implementing team matchmaking. We need to figure out map pools there anyways and as the system is being restructured anyways (probably making 1v1 ladder a queue of the matchmaker), we should take that opportunity to give map pools a deep thought. We should probably debate that somewhere (either in a conference or in e.g. the tmm discussions channel) with more people.

**Comment by FtXCommando** [comment] 2020-01-29 22:32
As far as I'm aware the veto system went away way back in 2014 when a lot of people asked for its removal due to the fact it generally led to poor map selections. It was more a problem of the way that zep structured the way the ladder system worked. 

If we want to talk about the way to structure map pools, the choice pool system I thought of a year ago (which would basically be the veto system of old while eliminating some of the failures of that system) could be looked at again. If it's too complicated/annoying to code in, we could use a more simple solution. But this would be, as geo said, something to talk about more in depth with more people.

**Comment by Askaholic** [comment] 2020-05-17 04:00
Addressed by #568

**Closed by Askaholic** 2020-05-17 04:00 UTC
