### ISSUE TITLE
Rating change for ineligible game

### ISSUE THREAD

**Issue by EricBurnett** [FAForever/server#328] opened 2017-11-22 03:08 UTC
http://content.faforever.com/faf/vault/replay_vault/replay.php?id=7083170 (I'm Whisker). FAF standard; only UI mods active.

This game should have been unranked from the start: it was two humans and two AI. On top of that:
 - Game did not end conclusively (we aborted when we realized we messed up the teams and were opposite each other)
 - Both teams (i.e. both players) saw positive rating change.

You are welcome to undo or leave the rating change as you see fit (one game won't be material either way), but it does seem like there's a glitch if we can play inconclusive games with AI and both gain rank over it :).

I have not attempted to see if this is repeatable.

Cheers,
Eric

**Comment by micheljung** [comment] 2017-11-22 11:26
When you "aborted", how quickly did you two leave the game?

I'm not sure whether such AI should be rated or not; if there is 1 human & 1 AI vs another human & AI, it seems pretty fair and "ratable" to me (given that the AIs are the same difficulty).

And when one player quits the game earlier than the other, the other player sees the first player explode, wins and reports this result to the server. Resulting in a rated game.

I didn't look at the code, however.

**Comment by Sheeo** [comment] 2017-11-22 11:31
Because you were playing on opposite teams, the codebase does indeed consider it a fair game [despite there being AI's](https://github.com/FAForever/server/blob/develop/server/games/game.py#L524).

**Comment by EricBurnett** [comment] 2017-11-22 18:37
Michel: We both quit about 11m in - spent some time ecoing on our respective islands, then realized our mistake.

W.r.t. one party winning, we may have quit too close together in time then. Because if one of us saw a win, the other should have seen a loss, but we both gained score. (Unless for 0-game players even a loss can cause a score increase? They were sufficiently large - +300 and +200 or so - that I'd be surprised, but it's possible.) I wonder if it was more that the last party to quit didn't lose, but didn't see the opponent explode either, so we both were considered to have won?

Sheeo: thanks, that's good to know. I got my information from the Scoreboard mod iirc, I'll look into filing a bug to them that there's more nuance than just "any AI present".

**Comment by Rackover** [comment] 2019-01-01 11:43
AIs now automatically unrank the game, aswell as other parameters.
Did you manage to reproduce the bug ?
If no, I'm closing.

**Closed** 2019-02-08 22:46 UTC
