### ISSUE TITLE
Problems with No Repetition Code

### ISSUE THREAD

**Issue by FtXCommando** [FAForever/server#624] opened 2020-07-07 20:32 UTC
It seems that the no repetition code that has people not play one of their last 3 maps is no longer functioning with the introduction of the new pools. I'm noticing people playing the same map repeatedly. 

I don't think it has anything to do with people transitioning between pools and the code considering the same map in two different pools to be two different maps as the example below consists of two people facing one another for two games in a row on the same map twice in a row. They should have had the same map pool for both games. They were both also 1400 (rounded) in both games, meaning they were not on the edge of switching between two pools.

I also don't think it has anything to do with the code bugging out due to there being no viable map to pick, as the smallest map pool is 7 which means in the worst case scenario, there is still 1 viable map for the code to pick with the 3 map restriction. 

![repeat](https://user-images.githubusercontent.com/43039749/86839432-6bc1fe80-c06f-11ea-98c2-a8c53cc5a305.png)

**Comment by Askaholic** [comment] 2020-07-07 23:31
Thanks FTX!

I think this definitely has something to do with it:
https://github.com/FAForever/server/blob/83a1b48bdd4215818efe46db08dbf733641974e1/server/ladder_service.py#L468

those lines should be inside the for loop otherwise only the game data for the last player in the list will be queried. We will have to write some more unit tests to cover this condition.

**Comment by devopsdeluxe** [comment] 2020-07-11 22:52
@Askaholic I'd be happy to take a look into this

**Comment by Askaholic** [comment] 2020-11-11 04:40
According to @FtXCommando this is still an issue on the most recent server version.

![repetition](https://cdn.discordapp.com/attachments/202928463076786176/774362578809389086/rep.png)

**Comment by 0x647262** [comment] 2020-11-11 04:55
@Askaholic mind reassigning this to me?

**Comment by Askaholic** [comment] 2020-11-11 05:00
Sure! I have no leads for you this time though; no idea why it's not working.

**Comment by Askaholic** [comment] 2020-11-11 05:01
Really, you think it's `choose_map`? I thought I had written some good tests for that :P

**Comment by 0x647262** [comment] 2020-11-11 05:19
Just a hunch for now... `ladder_service.py`is still a suspect as well, as we could still just be feeding `choose_map` bad data.

**Comment by Askaholic** [comment] 2020-11-11 05:28
That would have been my guess. I also though that maybe the map pool was just too small, but I don't think so. It seems that the smallest map pool has 7 maps which is enough for both players to throw out 3 maps and still have 1 that neither has played recently.

**Comment by 0x647262** [comment] 2020-11-13 03:27
After a bit of testing I'm 100% certain we're feeding the `choose_map` function garbage data. The pool (or ladder anti-repetition limit) has to be _just_ small (or large, in the case of the ladder anti-repetition limit) enough to allow `choose_map` to offer up a repeat map.

**Comment by Askaholic** [comment] 2021-04-01 03:09
I think I found the issue. The problem is actually that the map pools themselves are being fetched incorrectly. In particular they are fetching map id's instead of map *version* id's. See here:

https://github.com/FAForever/server/blob/4a39a48966bf81fb1617506575de2e4eaa50d399/server/ladder_service.py#L110
This should be `map_version.c.id` since `map_version.c.map_id` is just the foreign key reference to `map.id`.

So what happens is that the map paths are still correct for a particular map version, but the id's are just completely wrong. Since the game code actually looks up the version id from the map path when writing the `game_stats` entry, the game history still uses the correct map_version ids. But when the map pool sees those ids they don't show up in the map list, so it ignores them all and just picks a random map. 

I looked at the git blame and it looks like this has been happening ever since we implemented the new map pools. Which was almost a year ago.

**Closed** 2021-04-01 20:20 UTC
Labels: bug
