### ISSUE TITLE
Add statsd metrics for connectivity

### ISSUE THREAD

**Issue by Sheeo** [FAForever/server#218] opened 2016-10-06 11:30 UTC
Report connections made by STUN / TURN respectively.

**Comment by micheljung** [comment] 2016-11-21 14:15
Since this decision is no longer made by the server, we can't measure it (except we let the client report it)

**Comment by micheljung** [comment] 2016-11-23 01:05
Actually that's a duplicate of #192

**Closed by micheljung** 2016-11-23 01:05 UTC
