### ISSUE TITLE
Crash during connectivity check

### ISSUE THREAD

**Issue by micheljung** [FAForever/server#104] opened 2015-12-18 16:09 UTC
DEBUG:server.lobbyconnection.LobbyConnection:<<: {'target': 'connectivity', 'args': [6112], 'command': 'InitiateTest'}
    DEBUG:server.connectivity.ConnectivityTest:Testing PUBLIC
    DEBUG:server.natpacketserver.NatPacketServer:>>('46.126.105.89', 6112)/udp: Are you public? 21447
    ERROR:asyncio:Task exception was never retrieved
    future: <Task finished coro=<Connectivity.initiate_test() done, defined at /code/server/connectivity.py:83> exception=AttributeError("'NoneType' object has no attribute 'call_exception_handler'",)>
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/asyncio/selector_events.py", line 1029, in sendto
        self._sock.sendto(data, addr)
    AttributeError: 'NoneType' object has no attribute 'sendto'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/asyncio/tasks.py", line 239, in _step
        result = coro.send(value)
      File "/code/server/connectivity.py", line 85, in initiate_test
        result = await self._test.determine_connectivity()
      File "/code/server/connectivity.py", line 199, in determine_connectivity
        public = await self.test_public()
      File "/code/server/connectivity.py", line 216, in test_public
        await send_natpacket(self.remote_addr, message)
      File "/code/server/connectivity.py", line 23, in send_natpacket
        _natserver.send_natpacket_to(msg, addr)
      File "/code/server/natpacketserver.py", line 69, in send_natpacket_to
        self.protocol.transport.sendto(("\x08"+msg).encode(), addr)
      File "/usr/local/lib/python3.5/asyncio/selector_events.py", line 1038, in sendto
        'Fatal write error on datagram transport')
      File "/usr/local/lib/python3.5/asyncio/selector_events.py", line 584, in _fatal_error
        self._loop.call_exception_handler({
    AttributeError: 'NoneType' object has no attribute 'call_exception_handler'

**Comment by Sheeo** [comment] 2016-01-21 08:00
Seems to be duplicate of #110

**Closed by Sheeo** 2016-01-21 08:00 UTC
Labels: bug
