### ISSUE TITLE
FAF client is issuing wrongful connection violations for issues in connection that it itself caused

### ISSUE THREAD

**Issue by tatsujb** [FAForever/server#908] opened 2022-06-10 12:36 UTC
this is the second time this has happened to me. FA fails to connect with the other player and then when it finally closes back on FAF there's a popup waiting for me saying i've been issued a violation.

how is that fair?

also this is darn pattern

**Comment by Sheikah45** [comment] 2022-06-10 12:37
Why are you claiming the client caused the connection issue? If you can't connect to the host that is an issue with your connection and the system is operating as intended

**Comment by tatsujb** [comment] 2022-06-10 12:37
the UX of this is that the user has no head's up that the server is messing up and then gets punished for it. it's utterly stupid. fix the the connection issues instead.

**Comment by Sheikah45** [comment] 2022-06-10 14:28
> the UX of this is that the user has no head's up that the server is messing up and then gets punished for it. it's utterly stupid. fix the connection issues instead.

The server is not messing up the connection in any way. It is just observing if you are connected to the host as it is all peer to peer. I am not sure why you think the server is messing up the connection?

The only thing the server has is a timeout where if you don't connect in 3 minutes it calls it failed as otherwise people would sit there forever which is reasonable.

**Comment by Sheikah45** [comment] 2022-06-10 16:14
> because it's nothing on my end
> 
> sometimes it even starts a game and has me sitting on waiting for the other player while the other is able to type and is waiting for me.
> why?

If you can't connect then it is something on your end definitely. In a 1-to-1 connection you just can't connect to each other.

**Comment by Askaholic** [comment] 2022-06-10 19:14
The lobby server can't cause your game to fail to connect. If you're not connecting it's an issue between your network, ICE and the other player's network. All the lobby server can do is observe the fact that you didn't connect to the host and issue a violation. There will be some false positives which is why we don't issue any penalty until the second violation. If this happens too often and we need to up the number of unpenalized violations we can discuss that separately, but I don't see an actual server bug described here so I'm closing this issue.

**Closed by Askaholic** 2022-06-10 19:14 UTC

**Comment by tatsujb** [comment] 2022-06-13 10:45
well all I've gotten is false positives as I'd define them. there's no way this is my fault.

**Comment by BlackYps** [comment] 2022-06-18 15:24
How do you know that it is not your fault? Having a generally stable internet connection is not a sufficient criterion to judge this. You connect peer to peer to a random person anywhere in the world, it is possible that bad routing or a shitty ISP makes a connection fail sometimes.

Are we talking about 1v1 or team games here btw?

**Comment by tatsujb** [comment] 2023-01-20 01:04
Just happened twice again.

Definitely not my fault because FAF is even issuing out confusing messaging : 
![Screenshot from 2023-01-20 02-02-26](https://user-images.githubusercontent.com/5132359/213595923-214024f8-0f3d-4802-95a3-0dedff26b281.png)
![Screenshot from 2023-01-20 02-02-32](https://user-images.githubusercontent.com/5132359/213595926-e23ad1d6-13c7-4245-87f5-800e2e166de6.png)
I get both these error messages one on top of the other and they both contradict each other.

**Comment by tatsujb** [comment] 2023-02-25 12:38
it just keeps happening every time it's more wrong than the last

this time FA sais the two players are using a different client version. 
this is not my fault. I'm using 2023.1.2 that's the current correct version.

the people using the many different pre-releases are the ones in the wrong and shouldn't be queuing up for ladder. I shoulnd't be getting the warning nor the 10 min matchmaking ban.

please lift my matchmaking ban

**Comment by BlackYps** [comment] 2023-02-25 12:49
What we could do is not giving out violations for 1v1 matchmaking. The host is assigned randomly and if the connection fails the person that is not the host will get issued a violation. But with only a single connection it is impossible to tell who of the two ends is to blame.

**Comment by tatsujb** [comment] 2023-02-25 13:45
yeah this whole thing is utterly devoid of any logic, testing or idiot-proofing

**Comment by Askaholic** [comment] 2023-02-25 15:46
@tatsujb I understand that you are frustrated but that is completely untrue and you know that. Please keep GitHub discussions civil and on topic.
